# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/htc_imeuhl/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/htc_imeuhl/proprietary/bin/wfdservice:system/bin/wfdservice \
    vendor/htc/htc_imeuhl/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    vendor/htc/htc_imeuhl/proprietary/etc/firmware/ILP0100_IPM_Code_out.bin:system/etc/firmware/ILP0100_IPM_Code_out.bin \
    vendor/htc/htc_imeuhl/proprietary/etc/firmware/ILP0100_IPM_Data_out.bin:system/etc/firmware/ILP0100_IPM_Data_out.bin \
    vendor/htc/htc_imeuhl/proprietary/etc/firmware/alIAF_InData_4M2M:system/etc/firmware/alIAF_InData_4M2M \
    vendor/htc/htc_imeuhl/proprietary/etc/firmware/lscbuffer_rev2.bin:system/etc/firmware/lscbuffer_rev2.bin \
    vendor/htc/htc_imeuhl/proprietary/etc/init/dpmd.rc:system/etc/init/dpmd.rc \
    vendor/htc/htc_imeuhl/proprietary/etc/init/wfdservice.rc:system/etc/init/wfdservice.rc \
    vendor/htc/htc_imeuhl/proprietary/etc/nfcee_access.xml:system/etc/nfcee_access.xml \
    vendor/htc/htc_imeuhl/proprietary/etc/permissions/audiosphere.xml:system/etc/permissions/audiosphere.xml \
    vendor/htc/htc_imeuhl/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/htc/htc_imeuhl/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    vendor/htc/htc_imeuhl/proprietary/etc/permissions/com.qti.location.sdk.xml:system/etc/permissions/com.qti.location.sdk.xml \
    vendor/htc/htc_imeuhl/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/htc/htc_imeuhl/proprietary/etc/permissions/com.qualcomm.qti.imscmservice.xml:system/etc/permissions/com.qualcomm.qti.imscmservice.xml \
    vendor/htc/htc_imeuhl/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    vendor/htc/htc_imeuhl/proprietary/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
    vendor/htc/htc_imeuhl/proprietary/etc/permissions/izat.xt.srv.xml:system/etc/permissions/izat.xt.srv.xml \
    vendor/htc/htc_imeuhl/proprietary/etc/permissions/privapp-permissions-com.qualcomm.location.xml:system/etc/permissions/privapp-permissions-com.qualcomm.location.xml \
    vendor/htc/htc_imeuhl/proprietary/etc/permissions/privapp-permissions-qti.xml:system/etc/permissions/privapp-permissions-qti.xml \
    vendor/htc/htc_imeuhl/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/htc/htc_imeuhl/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/htc/htc_imeuhl/proprietary/etc/permissions/telephonyservice.xml:system/etc/permissions/telephonyservice.xml \
    vendor/htc/htc_imeuhl/proprietary/etc/sysconfig/qti_whitelist.xml:system/etc/sysconfig/qti_whitelist.xml \
    vendor/htc/htc_imeuhl/proprietary/etc/wfdconfig.xml:system/etc/wfdconfig.xml \
    vendor/htc/htc_imeuhl/proprietary/etc/wfdconfigsink.xml:system/etc/wfdconfigsink.xml \
    vendor/htc/htc_imeuhl/proprietary/framework/QtiTelephonyServicelibrary.jar:system/framework/QtiTelephonyServicelibrary.jar \
    vendor/htc/htc_imeuhl/proprietary/framework/audiosphere.jar:system/framework/audiosphere.jar \
    vendor/htc/htc_imeuhl/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    vendor/htc/htc_imeuhl/proprietary/framework/com.qti.dpmframework.jar:system/framework/com.qti.dpmframework.jar \
    vendor/htc/htc_imeuhl/proprietary/framework/com.qti.location.sdk.jar:system/framework/com.qti.location.sdk.jar \
    vendor/htc/htc_imeuhl/proprietary/framework/com.qualcomm.qti.imscmservice@1.0-java.jar:system/framework/com.qualcomm.qti.imscmservice@1.0-java.jar \
    vendor/htc/htc_imeuhl/proprietary/framework/com.quicinc.cne.api-V1.0-java.jar:system/framework/com.quicinc.cne.api-V1.0-java.jar \
    vendor/htc/htc_imeuhl/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
    vendor/htc/htc_imeuhl/proprietary/framework/dpmapi.jar:system/framework/dpmapi.jar \
    vendor/htc/htc_imeuhl/proprietary/framework/embmslibrary.jar:system/framework/embmslibrary.jar \
    vendor/htc/htc_imeuhl/proprietary/framework/izat.xt.srv.jar:system/framework/izat.xt.srv.jar \
    vendor/htc/htc_imeuhl/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/htc/htc_imeuhl/proprietary/framework/tcmclient.jar:system/framework/tcmclient.jar \
    vendor/htc/htc_imeuhl/proprietary/lib/com.qualcomm.qti.ant@1.0.so:system/lib/com.qualcomm.qti.ant@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib/com.qualcomm.qti.dpm.api@1.0.so:system/lib/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib/com.qualcomm.qti.imscmservice@1.0.so:system/lib/com.qualcomm.qti.imscmservice@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib/com.qualcomm.qti.wifidisplayhal@1.0.so:system/lib/com.qualcomm.qti.wifidisplayhal@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib/fm_helium.so:system/lib/fm_helium.so \
    vendor/htc/htc_imeuhl/proprietary/lib/lib-imsvideocodec.so:system/lib/lib-imsvideocodec.so \
    vendor/htc/htc_imeuhl/proprietary/lib/lib-imsvt.so:system/lib/lib-imsvt.so \
    vendor/htc/htc_imeuhl/proprietary/lib/lib-imsvtextutils.so:system/lib/lib-imsvtextutils.so \
    vendor/htc/htc_imeuhl/proprietary/lib/lib-imsvtutils.so:system/lib/lib-imsvtutils.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libFileMux.so:system/lib/libFileMux.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libOmxMux.so:system/lib/libOmxMux.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libaptXHD_encoder.so:system/lib/libaptXHD_encoder.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libaptX_encoder.so:system/lib/libaptX_encoder.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libchromaflash.so:system/lib/libchromaflash.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libdiag_system.so:system/lib/libdiag_system.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libdpmctmgr.so:system/lib/libdpmctmgr.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libdpmfdmgr.so:system/lib/libdpmfdmgr.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libdpmframework.so:system/lib/libdpmframework.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libdpmnsrm.so:system/lib/libdpmnsrm.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libdpmtcm.so:system/lib/libdpmtcm.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libfm-hci.so:system/lib/libfm-hci.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libimscamera_jni.so:system/lib/libimscamera_jni.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libimsmedia_jni.so:system/lib/libimsmedia_jni.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libmmparser_lite.so:system/lib/libmmparser_lite.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libmmrtpdecoder.so:system/lib/libmmrtpdecoder.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libmmrtpencoder.so:system/lib/libmmrtpencoder.so \
    vendor/htc/htc_imeuhl/proprietary/lib/librcc.so:system/lib/librcc.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libscveBlobDescriptor.so:system/lib/libscveBlobDescriptor.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libscveBlobDescriptor_stub.so:system/lib/libscveBlobDescriptor_stub.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libscveCommon.so:system/lib/libscveCommon.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libscveCommon_stub.so:system/lib/libscveCommon_stub.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libscveFaceLandmarks.so:system/lib/libscveFaceLandmarks.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libscveFaceRecognition.so:system/lib/libscveFaceRecognition.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libscveImageCorrection.so:system/lib/libscveImageCorrection.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libscveObjectSegmentation.so:system/lib/libscveObjectSegmentation.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libscveObjectTracker.so:system/lib/libscveObjectTracker.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libscveObjectTracker_stub.so:system/lib/libscveObjectTracker_stub.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libscvePanorama.so:system/lib/libscvePanorama.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libscvePanorama_lite.so:system/lib/libscvePanorama_lite.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libscveScan3D.so:system/lib/libscveScan3D.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libwfdavenhancements.so:system/lib/libwfdavenhancements.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libwfdcodecv4l2.so:system/lib/libwfdcodecv4l2.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libwfdcommonutils.so:system/lib/libwfdcommonutils.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libwfdconfigutils.so:system/lib/libwfdconfigutils.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libwfdmminterface.so:system/lib/libwfdmminterface.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libwfdmmsink.so:system/lib/libwfdmmsink.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libwfdmmsrc.so:system/lib/libwfdmmsrc.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libwfdnative.so:system/lib/libwfdnative.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libwfdrtsp.so:system/lib/libwfdrtsp.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libwfdservice.so:system/lib/libwfdservice.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libwfdsm.so:system/lib/libwfdsm.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libwfduibcinterface.so:system/lib/libwfduibcinterface.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libwfduibcsink.so:system/lib/libwfduibcsink.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libwfduibcsinkinterface.so:system/lib/libwfduibcsinkinterface.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libwfduibcsrc.so:system/lib/libwfduibcsrc.so \
    vendor/htc/htc_imeuhl/proprietary/lib/libwfduibcsrcinterface.so:system/lib/libwfduibcsrcinterface.so \
    vendor/htc/htc_imeuhl/proprietary/lib/rfsa/adsp/libscveBlobDescriptor_skel.so:system/lib/rfsa/adsp/libscveBlobDescriptor_skel.so \
    vendor/htc/htc_imeuhl/proprietary/lib/rfsa/adsp/libscveT2T_skel.so:system/lib/rfsa/adsp/libscveT2T_skel.so \
    vendor/htc/htc_imeuhl/proprietary/lib/vendor.display.color@1.0.so:system/lib/vendor.display.color@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib/vendor.display.postproc@1.0.so:system/lib/vendor.display.postproc@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib/vendor.qti.esepowermanager@1.0.so:system/lib/vendor.qti.esepowermanager@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib/vendor.qti.gnss@1.0.so:system/lib/vendor.qti.gnss@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib/vendor.qti.gnss@1.1.so:system/lib/vendor.qti.gnss@1.1.so \
    vendor/htc/htc_imeuhl/proprietary/lib/vendor.qti.hardware.data.latency@1.0.so:system/lib/vendor.qti.hardware.data.latency@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib/vendor.qti.hardware.vpp@1.1.so:system/lib/vendor.qti.hardware.vpp@1.1.so \
    vendor/htc/htc_imeuhl/proprietary/lib/vendor.qti.imsrtpservice@1.0.so:system/lib/vendor.qti.imsrtpservice@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/com.qualcomm.qti.ant@1.0.so:system/lib64/com.qualcomm.qti.ant@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/com.qualcomm.qti.dpm.api@1.0.so:system/lib64/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/com.qualcomm.qti.imscmservice@1.0.so:system/lib64/com.qualcomm.qti.imscmservice@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/com.qualcomm.qti.wifidisplayhal@1.0.so:system/lib64/com.qualcomm.qti.wifidisplayhal@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/fm_helium.so:system/lib64/fm_helium.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/lib-imsvideocodec.so:system/lib64/lib-imsvideocodec.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/lib-imsvt.so:system/lib64/lib-imsvt.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/lib-imsvtextutils.so:system/lib64/lib-imsvtextutils.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/lib-imsvtutils.so:system/lib64/lib-imsvtutils.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libFileMux.so:system/lib64/libFileMux.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libOmxMux.so:system/lib64/libOmxMux.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libaptXHD_encoder.so:system/lib64/libaptXHD_encoder.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libaptX_encoder.so:system/lib64/libaptX_encoder.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libdiag_system.so:system/lib64/libdiag_system.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libdpmctmgr.so:system/lib64/libdpmctmgr.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libdpmfdmgr.so:system/lib64/libdpmfdmgr.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libdpmframework.so:system/lib64/libdpmframework.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libdpmnsrm.so:system/lib64/libdpmnsrm.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libdpmtcm.so:system/lib64/libdpmtcm.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libfm-hci.so:system/lib64/libfm-hci.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libimscamera_jni.so:system/lib64/libimscamera_jni.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libimsmedia_jni.so:system/lib64/libimsmedia_jni.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/liblocationservice_jni.so:system/lib64/liblocationservice_jni.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libmmosal.so:system/lib64/libmmosal.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libmmparser_lite.so:system/lib64/libmmparser_lite.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libmmrtpdecoder.so:system/lib64/libmmrtpdecoder.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libmmrtpencoder.so:system/lib64/libmmrtpencoder.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/librcc.so:system/lib64/librcc.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libscveBlobDescriptor.so:system/lib64/libscveBlobDescriptor.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libscveBlobDescriptor_stub.so:system/lib64/libscveBlobDescriptor_stub.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libscveCommon.so:system/lib64/libscveCommon.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libscveCommon_stub.so:system/lib64/libscveCommon_stub.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libscveFaceLandmarks.so:system/lib64/libscveFaceLandmarks.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libscveFaceRecognition.so:system/lib64/libscveFaceRecognition.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libscveImageCorrection.so:system/lib64/libscveImageCorrection.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libscveObjectSegmentation.so:system/lib64/libscveObjectSegmentation.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libscveObjectTracker.so:system/lib64/libscveObjectTracker.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libscveObjectTracker_stub.so:system/lib64/libscveObjectTracker_stub.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libscvePanorama.so:system/lib64/libscvePanorama.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libscvePanorama_lite.so:system/lib64/libscvePanorama_lite.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libscveScan3D.so:system/lib64/libscveScan3D.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libseemore.so:system/lib64/libseemore.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libwfdavenhancements.so:system/lib64/libwfdavenhancements.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libwfdcodecv4l2.so:system/lib64/libwfdcodecv4l2.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libwfdcommonutils.so:system/lib64/libwfdcommonutils.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libwfdconfigutils.so:system/lib64/libwfdconfigutils.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libwfdmminterface.so:system/lib64/libwfdmminterface.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libwfdmmsink.so:system/lib64/libwfdmmsink.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libwfdmmsrc.so:system/lib64/libwfdmmsrc.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libwfdnative.so:system/lib64/libwfdnative.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libwfdrtsp.so:system/lib64/libwfdrtsp.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libwfdservice.so:system/lib64/libwfdservice.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libwfdsm.so:system/lib64/libwfdsm.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libwfduibcinterface.so:system/lib64/libwfduibcinterface.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libwfduibcsink.so:system/lib64/libwfduibcsink.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libwfduibcsinkinterface.so:system/lib64/libwfduibcsinkinterface.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libwfduibcsrc.so:system/lib64/libwfduibcsrc.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libwfduibcsrcinterface.so:system/lib64/libwfduibcsrcinterface.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/libxt_native.so:system/lib64/libxt_native.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/vendor.display.color@1.0.so:system/lib64/vendor.display.color@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/vendor.display.postproc@1.0.so:system/lib64/vendor.display.postproc@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/vendor.qti.esepowermanager@1.0.so:system/lib64/vendor.qti.esepowermanager@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/vendor.qti.gnss@1.0.so:system/lib64/vendor.qti.gnss@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/vendor.qti.gnss@1.1.so:system/lib64/vendor.qti.gnss@1.1.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/vendor.qti.hardware.data.latency@1.0.so:system/lib64/vendor.qti.hardware.data.latency@1.0.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/vendor.qti.hardware.vpp@1.1.so:system/lib64/vendor.qti.hardware.vpp@1.1.so \
    vendor/htc/htc_imeuhl/proprietary/lib64/vendor.qti.imsrtpservice@1.0.so:system/lib64/vendor.qti.imsrtpservice@1.0.so

PRODUCT_PACKAGES += \
    libantradio \
    libsdm-disp-apis \
    vendor.qti.hardware.fm@1.0 \
    QtiTelephonyService \
    embms \
    CNEService \
    HotwordEnrollmentOKGoogleWCD9340 \
    HotwordEnrollmentTGoogleWCD9340 \
    HotwordEnrollmentXGoogleWCD9340 \
    qcrilmsgtunnel \
    WfdCommon
